# Generated by Django 5.2.8 on 2025-12-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_options_alter_deliveryboy_options'),
        ('comments', '0002_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='reactions_dislike', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='reactions_like', to='accounts.customer'),
        ),
    ]
