# Generated by Django 5.2.8 on 2025-12-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
