# Generated by Django 5.2.8 on 2025-12-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_join_date_deliveryboy_join_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='deliveryboy',
            options={'ordering': ['-id']},
        ),
    ]
