# Generated by Django 5.2.8 on 2025-12-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in-progress', 'in-progess'), ('resolved', 'resolved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
