# Generated by Django 5.2.8 on 2025-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_latitude_alter_order_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
