# Generated by Django 5.2.8 on 2025-12-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_latitude_alter_order_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('delivered', 'delivered')], default='pending', max_length=30),
        ),
    ]
