# Generated by Django 5.2.8 on 2025-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('ongoing', 'ongoing'), ('delivered', 'delivered')], default='pending', max_length=30),
        ),
    ]
