# Generated by Django 5.2.8 on 2025-12-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('return_requested', 'return_requested'), ('cancelled', 'cancelled'), ('ongoing', 'ongoing'), ('delivered', 'delivered')], default='pending', max_length=30),
        ),
    ]
