# Generated by Django 5.2.8 on 2025-12-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_delivered_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
