# Generated by Django 5.2.8 on 2025-12-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brand_images/')),
                ('brand_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('category_slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_description', models.TextField()),
                ('product_price', models.PositiveIntegerField(default=0)),
                ('product_inventory', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_price', models.PositiveIntegerField(blank=True, null=True)),
                ('discounted_price', models.PositiveIntegerField(blank=True, null=True)),
                ('has_discounted', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category')),
            ],
        ),
    ]
